from reportlab.lib.styles import ParagraphStyle
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.platypus import SimpleDocTemplate, Paragraph


def create_pdf(input_text, output_filename):
    pdf = SimpleDocTemplate(output_filename, pagesize=letter)
    styles = getSampleStyleSheet()
    justified_style = ParagraphStyle(
        "Justified",
        parent=styles["Normal"],
        alignment=0,
        spaceBefore=12,
        spaceAfter=12,
    )
    story = []
    paragraphs = input_text.split('\n')
    for paragraph in paragraphs:
        story.append(Paragraph(paragraph, justified_style))
    pdf.build(story)


t = """
In the sweltering heat of early July, a young man emerges from his cramped garret in S. Place, contemplating a hesitant stroll towards K. Bridge. To avoid his landlady, he navigates the stairs and passes her ever-open kitchen door, evoking a mix of sickness, fear, scowling, and shame. Despite his debt, his current state of irritability and isolation makes him dread encounters with anyone, including his landlady. Poverty weighs less on him now, as he has abandoned practical matters and lost the will to engage. The prospect of his landlady's actions holds no genuine terror for him.
The young man, overwhelmed by anxiety and the oppressive atmosphere of the city, contemplates taking a significant step but is hindered by fear. He reflects on the power of taking action and the fear associated with it. Amidst the unpleasant surroundings, he questions his own capabilities and the seriousness of his intentions, dismissing them as mere fantasies.
The young man, despite his exceptional handsomeness, was in a state of profound disgust and deep thought, bordering on blankness of mind. He was poorly dressed, but in a neighborhood where various types of people were seen, his appearance did not cause surprise. However, he felt bitterness and contempt in his heart and minded his rags the least. He disliked meeting acquaintances or former fellow students, but he encountered a drunken man being taken somewhere in a waggon.
The young man is worried that his hat will draw attention to him and ruin his plan. He believes that he should wear a cap instead, as it would be less noticeable. He is fixated on the details and believes that even small things can ruin everything. He is also aware of the exact number of steps from his lodging house to his destination, which he had counted while lost in dreams. Despite his self-doubt, he has begun to consider his dream as an exploit to be attempted.
The man, unaware of his true intentions, excitedly approaches a large tenement house. He slips through a back staircase, familiar with the surroundings and appreciating the darkness. Reaching the fourth floor, he encounters porters moving furniture out of a flat previously occupied by a German clerk. Pleased that the floor will be mostly empty, he rings the bell of the old woman's flat.
The young man, Raskolnikov, visits an old woman's apartment. She is suspicious of him at first but opens the door when she sees others on the landing. Raskolnikov notices her sharp eyes, grizzled hair, and mangy fur cape. She coughs and groans constantly. He introduces himself and reminds her of his previous visit. The old woman acknowledges remembering him.
Raskolnikov visits the old woman's apartment again and notices the room's details, including yellow wallpaper, geraniums, and muslin curtains. He thinks about the sun shining and quickly scans the room, but there's nothing special about it. The furniture is old and yellow, with a sofa, table, dressing table, chairs, and a few prints. A light burns before an ikon, and everything is clean and polished. Raskolnikov thinks that Lizaveta must have done the cleaning.
Raskolnikov visits a pawnbroker, Alyona Ivanovna, to pawn his father's watch. She offers him only a rouble and a half, which angers him.
The young man, in need of money, visits an old woman to pawn his watch. While she retrieves the money, he speculates about the keys she carries and the potential existence of a strongbox. Upon receiving a lower amount than expected, he accepts the money without argument and lingers, hinting at further conversation.
In the sweltering heat of early July, a young man emerges from his cramped garret in S. Place, contemplating a hesitant stroll towards K. Bridge. To avoid his landlady, he navigates the stairs and passes her ever-open kitchen door, evoking a mix of sickness, fear, scowling, and shame. Despite his debt, his current state of irritability and isolation makes him dread encounters with anyone, including his landlady. Poverty weighs less on him now, as he has abandoned practical matters and lost the will to engage. The prospect of his landlady's actions holds no genuine terror for him.
The young man, overwhelmed by anxiety and the oppressive atmosphere of the city, contemplates taking a significant step but is hindered by fear. He reflects on the power of taking action and the fear associated with it. Amidst the unpleasant surroundings, he questions his own capabilities and the seriousness of his intentions, dismissing them as mere fantasies.
The young man, despite his exceptional handsomeness, was in a state of profound disgust and deep thought, bordering on blankness of mind. He was poorly dressed, but in a neighborhood where various types of people were seen, his appearance did not cause surprise. However, he felt bitterness and contempt in his heart and minded his rags the least. He disliked meeting acquaintances or former fellow students, but he encountered a drunken man being taken somewhere in a waggon.
The young man is worried that his hat will draw attention to him and ruin his plan. He believes that he should wear a cap instead, as it would be less noticeable. He is fixated on the details and believes that even small things can ruin everything. He is also aware of the exact number of steps from his lodging house to his destination, which he had counted while lost in dreams. Despite his self-doubt, he has begun to consider his dream as an exploit to be attempted.
The man, unaware of his true intentions, excitedly approaches a large tenement house. He slips through a back staircase, familiar with the surroundings and appreciating the darkness. Reaching the fourth floor, he encounters porters moving furniture out of a flat previously occupied by a German clerk. Pleased that the floor will be mostly empty, he rings the bell of the old woman's flat.
The young man, Raskolnikov, visits an old woman's apartment. She is suspicious of him at first but opens the door when she sees others on the landing. Raskolnikov notices her sharp eyes, grizzled hair, and mangy fur cape. She coughs and groans constantly. He introduces himself and reminds her of his previous visit. The old woman acknowledges remembering him.
Raskolnikov visits the old woman's apartment again and notices the room's details, including yellow wallpaper, geraniums, and muslin curtains. He thinks about the sun shining and quickly scans the room, but there's nothing special about it. The furniture is old and yellow, with a sofa, table, dressing table, chairs, and a few prints. A light burns before an ikon, and everything is clean and polished. Raskolnikov thinks that Lizaveta must have done the cleaning.
Raskolnikov visits a pawnbroker, Alyona Ivanovna, to pawn his father's watch. She offers him only a rouble and a half, which angers him.
The young man, in need of money, visits an old woman to pawn his watch. While she retrieves the money, he speculates about the keys she carries and the potential existence of a strongbox. Upon receiving a lower amount than expected, he accepts the money without argument and lingers, hinting at further conversation.
In the sweltering heat of early July, a young man emerges from his cramped garret in S. Place, contemplating a hesitant stroll towards K. Bridge. To avoid his landlady, he navigates the stairs and passes her ever-open kitchen door, evoking a mix of sickness, fear, scowling, and shame. Despite his debt, his current state of irritability and isolation makes him dread encounters with anyone, including his landlady. Poverty weighs less on him now, as he has abandoned practical matters and lost the will to engage. The prospect of his landlady's actions holds no genuine terror for him.
The young man, overwhelmed by anxiety and the oppressive atmosphere of the city, contemplates taking a significant step but is hindered by fear. He reflects on the power of taking action and the fear associated with it. Amidst the unpleasant surroundings, he questions his own capabilities and the seriousness of his intentions, dismissing them as mere fantasies.
The young man, despite his exceptional handsomeness, was in a state of profound disgust and deep thought, bordering on blankness of mind. He was poorly dressed, but in a neighborhood where various types of people were seen, his appearance did not cause surprise. However, he felt bitterness and contempt in his heart and minded his rags the least. He disliked meeting acquaintances or former fellow students, but he encountered a drunken man being taken somewhere in a waggon.
The young man is worried that his hat will draw attention to him and ruin his plan. He believes that he should wear a cap instead, as it would be less noticeable. He is fixated on the details and believes that even small things can ruin everything. He is also aware of the exact number of steps from his lodging house to his destination, which he had counted while lost in dreams. Despite his self-doubt, he has begun to consider his dream as an exploit to be attempted.
The man, unaware of his true intentions, excitedly approaches a large tenement house. He slips through a back staircase, familiar with the surroundings and appreciating the darkness. Reaching the fourth floor, he encounters porters moving furniture out of a flat previously occupied by a German clerk. Pleased that the floor will be mostly empty, he rings the bell of the old woman's flat.
The young man, Raskolnikov, visits an old woman's apartment. She is suspicious of him at first but opens the door when she sees others on the landing. Raskolnikov notices her sharp eyes, grizzled hair, and mangy fur cape. She coughs and groans constantly. He introduces himself and reminds her of his previous visit. The old woman acknowledges remembering him.
Raskolnikov visits the old woman's apartment again and notices the room's details, including yellow wallpaper, geraniums, and muslin curtains. He thinks about the sun shining and quickly scans the room, but there's nothing special about it. The furniture is old and yellow, with a sofa, table, dressing table, chairs, and a few prints. A light burns before an ikon, and everything is clean and polished. Raskolnikov thinks that Lizaveta must have done the cleaning.
Raskolnikov visits a pawnbroker, Alyona Ivanovna, to pawn his father's watch. She offers him only a rouble and a half, which angers him.
The young man, in need of money, visits an old woman to pawn his watch. While she retrieves the money, he speculates about the keys she carries and the potential existence of a strongbox. Upon receiving a lower amount than expected, he accepts the money without argument and lingers, hinting at further conversation.
In the sweltering heat of early July, a young man emerges from his cramped garret in S. Place, contemplating a hesitant stroll towards K. Bridge. To avoid his landlady, he navigates the stairs and passes her ever-open kitchen door, evoking a mix of sickness, fear, scowling, and shame. Despite his debt, his current state of irritability and isolation makes him dread encounters with anyone, including his landlady. Poverty weighs less on him now, as he has abandoned practical matters and lost the will to engage. The prospect of his landlady's actions holds no genuine terror for him.
The young man, overwhelmed by anxiety and the oppressive atmosphere of the city, contemplates taking a significant step but is hindered by fear. He reflects on the power of taking action and the fear associated with it. Amidst the unpleasant surroundings, he questions his own capabilities and the seriousness of his intentions, dismissing them as mere fantasies.
The young man, despite his exceptional handsomeness, was in a state of profound disgust and deep thought, bordering on blankness of mind. He was poorly dressed, but in a neighborhood where various types of people were seen, his appearance did not cause surprise. However, he felt bitterness and contempt in his heart and minded his rags the least. He disliked meeting acquaintances or former fellow students, but he encountered a drunken man being taken somewhere in a waggon.
The young man is worried that his hat will draw attention to him and ruin his plan. He believes that he should wear a cap instead, as it would be less noticeable. He is fixated on the details and believes that even small things can ruin everything. He is also aware of the exact number of steps from his lodging house to his destination, which he had counted while lost in dreams. Despite his self-doubt, he has begun to consider his dream as an exploit to be attempted.
The man, unaware of his true intentions, excitedly approaches a large tenement house. He slips through a back staircase, familiar with the surroundings and appreciating the darkness. Reaching the fourth floor, he encounters porters moving furniture out of a flat previously occupied by a German clerk. Pleased that the floor will be mostly empty, he rings the bell of the old woman's flat.
The young man, Raskolnikov, visits an old woman's apartment. She is suspicious of him at first but opens the door when she sees others on the landing. Raskolnikov notices her sharp eyes, grizzled hair, and mangy fur cape. She coughs and groans constantly. He introduces himself and reminds her of his previous visit. The old woman acknowledges remembering him.
Raskolnikov visits the old woman's apartment again and notices the room's details, including yellow wallpaper, geraniums, and muslin curtains. He thinks about the sun shining and quickly scans the room, but there's nothing special about it. The furniture is old and yellow, with a sofa, table, dressing table, chairs, and a few prints. A light burns before an ikon, and everything is clean and polished. Raskolnikov thinks that Lizaveta must have done the cleaning.
Raskolnikov visits a pawnbroker, Alyona Ivanovna, to pawn his father's watch. She offers him only a rouble and a half, which angers him.
The young man, in need of money, visits an old woman to pawn his watch. While she retrieves the money, he speculates about the keys she carries and the potential existence of a strongbox. Upon receiving a lower amount than expected, he accepts the money without argument and lingers, hinting at further conversation.
"""

create_pdf(t,'output.pdf')